version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=localhost
      - DB_USER=root  # Make sure 'youruser' matches the username used by your app.
      - DB_PASSWORD=123456  # Make sure 'yourpassword' matches the password used by your app.
      - DB_NAME=expense_manager  # Make sure 'yourdbname' matches the database name used by your app.
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres  # It's common to use 'postgres' here.
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: expense_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
