version: '3.8'
services:
  app:
    container_name: expense_manager
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/expense_manager
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=expense_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
