version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=expense_manager
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: expense_manager
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
